### ISSUE TITLE
Language project registration

### ISSUE THREAD

**Issue by danixeee** [textX/textX-LS#13]
- [x] Implement a mechanism to install/uninstall textX language project using a [textX API](https://github.com/textX/textX/blob/master/textx/registration.py).
- [x] Generate and install VS Code extension for installed language project
- [x] Add custom activity bar with registered languages and generator

Useful links:
https://code.visualstudio.com/updates/v1_23#_custom-activity-bar-views
https://github.com/Microsoft/vscode-azureappservice

**Comment by danixeee** [comment]
textX explorer (VS Code) with _languages_ and _generators_ views:

<img width="346" alt="Screen Shot 2019-05-17 at 3 41 58 PM" src="https://user-images.githubusercontent.com/16227576/57932252-c8d28200-78ba-11e9-86dc-91d97b341d9a.png">

User can _install_, _remove_(not implemented) or _scaffold_ (not implemented) new language. "+" button opens file explorer and user can choose any wheel. This will install language in _non_-editable mode (e.g. `pip install my_dsl.wh;`).

![textX-LS](https://user-images.githubusercontent.com/16227576/57933003-6da18f00-78bc-11e9-8d29-f0f623c3ce88.gif)

Click [here](https://user-images.githubusercontent.com/16227576/57933003-6da18f00-78bc-11e9-8d29-f0f623c3ce88.gif) to open gif.

When language module is in the workspace, user can right click on either _module directory_ or _setup.py_ and install it from the context menu by choosing `Install textX language`. This will install language in _editable_ mode (`pip install -e path_to_module`), generate and install extension.

@igordejanovic @danielkupco  Thoughts?

**Comment by igordejanovic** [comment]
This looks really cool! I'm looking forward for this to be finished.

What happens when user changes the grammar of the language installed in *editable* mode? How the generated extension is reloaded? By reinstalling?

**Comment by danixeee** [comment]
Thank you!

> What happens when user changes the grammar of the language installed in editable mode? How the generated extension is reloaded? By reinstalling?

Nothing happens for now, but the plan is to increase the version and update the extension. I am not sure if that will work without reloading a window, probably not for now. For python packages it's easy, server will watch `.tx` files and it will just call `clear_language_registrations()`, to force reloading metamodel.

There are other tricky stuff, for e.g. I will need to keep `package-name`, because I can't uninstall language package by knowing just language name, etc...

**Comment by goto40** [comment]
After v2 is out I will update the example project. I would also like to try
out some editor features... Can you  recommend some Readme or/and a
specific feature branch for the editor support?

**Comment by danixeee** [comment]
@goto40 I just saw your comment, sorry. Some more work is needed to finish initial version for (un)installing languages from _textX-LS_ extension, validation and syntax highlighting.
I have changed build pipeline so it's failing, but every successful build should create a _vsix_ artifact which can be installed. I will create it manually this week and attach it somewhere, so you can try it out.

**Comment by goto40** [comment]
Take your time! No hurry.

**Comment by danixeee** [comment]
@igordejanovic @goto40 I was quite busy in the past months, so I haven't done anything major here. I was mostly reading and investigating a VS Code API and trying to find a way how to avoid restarting VS Code window after metamodel changes (in development).

Finally I was able to implement "hot-reload" feature, which is shown below.

![textx-ls-hot-reload-gif](https://user-images.githubusercontent.com/16227576/65926150-1841c680-e3f4-11e9-928f-4d08a633f9c3.gif)

**Comment by igordejanovic** [comment]
@danixeee Great work Daniel! I'm looking forward to use it / test it. How hard is it to install everything and set it up?
I think it would be great if I could introduce it with this generation of DSL course students so they could test it and provide feedback.

**Comment by danixeee** [comment]
@igordejanovic Thank you!

It should be pretty easy to set it up and try it, but we need to merge/release related work:

- https://github.com/danixeee/textx-gen-coloring/tree/danixeee/return-textmate-json
- https://github.com/danixeee/textx-gen-vscode/tree/danixeee/generate-extension-without-syntax
- https://github.com/textX/textX/tree/danixeee/textx-ls-integration-v0.1.0

We can pair anytime if you need any help.

**Comment by igordejanovic** [comment]
@danixeee Thanks. Please create PR for the textX part so that @goto40 and I could review the changes and prepare a new release.

**Comment by danixeee** [comment]
@igordejanovic After you release merged patch for _textX_ and I fix some minor issues for installing the extension, you will be able to download `.vsix` file from [here](https://dev.azure.com/textX/textX-LS/_build/results?buildId=392&view=results) (under _Build artifacts published_ section) and it should work without additional setup.

**Comment by igordejanovic** [comment]
@danixeee I installed `.vsix` from azure pipelines. I installed robot example from textX-LS project without problem but it seems that it's not working. I'm getting:
```
[Error - 9:49:22 PM] Request workspace/executeCommand failed.
  Message: TypeError: 'TextXMetaModel' object is not callable
  Code: -32602 
[object Object]
```

on each file or grammar change.

**Comment by goto40** [comment]
I assume, this is a python message... Are there additional log files to get a stack trace?

**Comment by igordejanovic** [comment]
I found logs in `~/.config/Code - OSS/logs` but no additional info even if I run VS code with `--log debug`.
I suspect that the problems arise due to usage of released version of textX instead of master.

@danixeee I saw in previous code plugin version that there was an option to configure used python3 executable but I can't see it now. I think it would be super useful to have that as we would be able to setup Python virtual environment with a particular version of textX (even installed from source) and give the executable from that environment. If this option is not provided system version would be used.  Am I missing something here?

**Comment by danixeee** [comment]
@igordejanovic 

> I suspect that the problems arise due to usage of released version of textX instead of master.

You are right, that is a reason for the error.

> Are there other ways to choose the virtual env I would like to run with?

For now, I am using python executable from sys path to create a virtual environment inside the extension and then I install install dependencies there. I just pushed [requirements-dev](https://github.com/textX/textX-LS/blob/danixeee/textx-view-container/client/wheels/requirements-dev.txt) which should [re-install](https://github.com/textX/textX-LS/blob/danixeee/textx-view-container/client/src/setup.ts#L60) needed _textX_ and _textx-gen-vscode_ deps. Anyway, it should be good idea to add support for using external venv.

> When I install a new language textX bar is not refreshed, I have to do it manually to see the new language. It would be nice if refresh would be done automatically on every language install/uninstall.

This already works if everything is installed correctly (installing python project + generating/installing VS Code extension). I just moved refresh command immediately after installing python project, so the list should be refreshed even if extension is not installed successfully (validation should work in that case).

> Although azure pipeline auto build is really great I would like to know how to build the .vsix file locally. I think that a step-by-step guide would really be nice to have in the docs.

Before I write some docs, there are just two steps:

1. `cd client & npm i`
2. `./node_modules/.bin/vsce package`

During packaging process, _core_ and _server_ wheels are [built and copied](https://github.com/textX/textX-LS/blob/danixeee/textx-view-container/client/bin/copy-wheels.sh) to `cliient/wheels` directory.

> I guess the next step would be project scaffolding and support for configuring and running generators?

That's the plan :)

**Comment by igordejanovic** [comment]
> For now, I am using python executable from sys path to create a virtual environment inside the extension and then I install install dependencies there. I just pushed [requirements-dev](https://github.com/textX/textX-LS/blob/danixeee/textx-view-container/client/wheels/requirements-dev.txt) which should [re-install](https://github.com/textX/textX-LS/blob/danixeee/textx-view-container/client/src/setup.ts#L60) needed _textX_ and _textx-gen-vscode_ deps. Anyway, it should be good idea to add support for using external venv.

Ah, thanks. That should suffice for now for testing purposes but it would really be great if external venv could be choosen. That way we could have full control which is important during development.
Where vscode creates virtual env? Can we `pip install` into that environment?

> That's the plan :)

Excellent! :)

**Comment by igordejanovic** [comment]
Ok, I've found the path of the virtual env on linux. It is `~/.vscode-oss/extensions/textx.textx-0.1.0+ed416f5e/textxls`. So it should be easy to manipulate the environment from CLI.

**Comment by danixeee** [comment]
@igordejanovic I think I finally fixed all major bugs.

You can download and try the latest vsix from [here](https://dev.azure.com/textX/textX-LS/_build/results?buildId=405&view=results).

Regarding logs, there is a file `~/.vscode-oss/extensions/textx.textx-0.1.0/textX.log` where you can find server logs and you can also open VS Code's _output channel_ and switch to `textX`. 

![image](https://user-images.githubusercontent.com/16227576/66356463-4894e200-e96b-11e9-8591-e8477a4f4ce3.png)

I need to add logging on the client, too. I plan to send them to the server, so we can have _one_ log file with chronological order of both _client_ and _server_ logs.

**Comment by igordejanovic** [comment]
Thanks. I'm still having issues but at least now everything seems to be logged in textX.log.

Here is the log from today's session.

[textX.log](https://github.com/textX/textX-LS/files/3701118/textX.log)

**Comment by danixeee** [comment]
Log seems fine. There are some error logs in a file, but those should be _warnings_ instead (from _pygls_).

Could you please go to `~/.vscode-oss/extensions` and manually remove all `textx` extension? Then open a VS Code and install the extension again. Let me know if it solves the problem

**Comment by igordejanovic** [comment]
Deleted extensions, started Code and installed vsix but still getting the same error:
```
[Error - 7:44:55 PM] Request workspace/executeCommand failed.
  Message: TypeError: 'TextXMetaModel' object is not callable
  Code: -32602 
[object Object]
```
robot extensions seems to be installed properly with version 0.1.0 when I choose `install textX project` from right click on `setup.py.`. Checked the generated environment and textX is installed with version 2.0.1.dev0 which should be the master version.
What I observe is that robot example is not fully colored. Comments and numbers are but keywords doesn't seems to be. Changing the grammar has no effects whatsoever to .rbt files. Can't get the behavior you demonstrated in the gif animation above.

**Comment by danixeee** [comment]
@igordejanovic My bad, I forgot to fix those examples. I am usually testing the extension with [this one](https://github.com/textX/textx-multi-metamodel-example).

Just pushed fixes for `Robot` and `Workflow` examples, so you can pull my changes and call `Install textX project` again (you don't need to reinstall anything).
You can either right click on `setup.py` or language project root directory (e.g. _examples/robot_).

We should validate if a [metamodel](https://github.com/textX/textX/blob/master/textx/registration.py#L31) of a registered language is a _callable_.

**Comment by igordejanovic** [comment]
That was it! Thanks! 

> We should validate if a metamodel of a registered language is a callable.

Agree.

BTW, should code completion work? When I delete the end of some of the keywords and press Ctrl+Space I don't get any suggestion.

**Comment by danixeee** [comment]
> That was it! Thanks!

Cool, hope it looks and works good now!

> BTW, should code completion work? When I delete the end of some of the keywords and press Ctrl+Space I don't get any suggestion.

It's not implemented yet, but this is now a solid base and it should be pretty easy to add other features.

This issue actually became a story and PR is going to be pretty big, but I am finally pleased with how it works.

I want to refactor code and add tests, but after we release a new `textX`, I could manually publish the extension to the marketplace to make it easily installable for course students.

**Comment by igordejanovic** [comment]
> It's not implemented yet, but this is now a solid base and it should be pretty easy to add other features.

Cool!

> This issue actually became a story and PR is going to be pretty big, but I am finally pleased with how it works.

Yeah, it works really good. There are some little issues I noticed but nothing critical. BTW, I suggest this PR to be merged to the master branch so it became more visible. It works good enough to be used and tested by the community and by merging to master It would be easier to contribute issue reports.

> I want to refactor code and add tests, but after we release a new textX, I could manually publish the extension to the marketplace to make it easily installable for course students.

That would be great. Thanks!

@goto40 If you agree we could make a new release of textX these days. I'll start a preparation.

**Comment by igordejanovic** [comment]
> We should validate if a metamodel of a registered language is a callable.

I was going to register the textX issue but recalled that we've changed slightly the semantics of a language metamodel to be either a callable or the metamodel itself. It is [in the docs](http://textx.github.io/textX/stable/registration/#language-registration-api).
If you are using the registration API to get to the meta-model you should be fine as it is checked [here](https://github.com/igordejanovic/textX/blob/master/textx/registration.py#L248).

**Comment by igordejanovic** [comment]
> Sure, I will just add some docs and merge it, probably during a following weekend.

Great. Thanks.

> If user caches a metamodel and always returns a same instance, I think we won't be able to reflect grammar changes without restarting the process. In any case, I am going to add that note to the docs.

I think you are right and besides note in the docs maybe Code plugin could provide a more informative error report if the metamodel is not callable (a warning stating that no refresh will be possible and a link to the docs).

**Comment by igordejanovic** [comment]
@danixeee textX 2.1.0 is out :)
